/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ConnectionsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "JWT_ACCESS_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JWT_REFRESH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RealtimeWs": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}